using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Constantes
{
    public class ConstantesGenerales
    {
        public const string ACUARIO = "ACUARIO";
        public const string ARIES = "ARIES";
        public const string CANCER = "CANCER";
        public const string CAPRICORNIO = "CAPRICORNIO";
        public const string ESCORPION = "ESCORPION";
        public const string GEMINIS = "GEMINIS";
        public const string LEO = "LEO";
        public const string LIBRA = "LIBRA";
        public const string PISCIS = "PISCIS";
        public const string SAGITARIO = "SAGITARIO";
        public const string TAURO = "TAURO";
        public const string VIRGO = "VIRGO";
        public const string POS_UNO = "POS_UNO";
        public const string POS_DOS = "POS_DOS";
        public const string POS_TRES = "POS_TRES";
        public const string POS_CUATRO = "POS_CUATRO";
        public const string SIGN = "SIGN";
        public const string ENCABEZADOS = ";PuntuacionTotal;UltimasRachas;UltimasRachasDespActual;ContadorUltimoEnRachas;DictRachasAgrupadasIntDespActual;DictRachasAgrupadasInt;ContadorUltimoEnRachasDesActual;ContadorGeneral;;ContadorDiaSemana;;ContadorDiaMes;;ContadorDiaModulo;;ContadorMes;;ContadorDiaAnio;;ContadorDiaAnioModulo;;ContadorMesModuloDiaModulo;;ContadorMesDia;;ContadorAnioModulo;;ContadorMesModulo;;ContadorDespuesActual;ContadorDespuesOtroTipo;ContadorDespuesSignActual";
        public const string INDICA_MIN_ULT_RACH = "INDICA_MIN_ULT_RACH";
        public const string INDICA_MIN_SIN_APARECER = "INDICA_MIN_SIN_APARECER";
        public const string COMPARA_ULT_RACH = "COMPARA_ULT_RACH";
        public const string INDICA_MIN_CONT_GENERAL = "INDICA_MIN_CONT_GENERAL";
        public const string COMPARA_CONT_GENERAL = "COMPARA_CONT_GENERAL";
        public const string INDICA_MIN_CONT_DIA_SEM = "INDICA_MIN_CONT_DIA_SEM";
        public const string COMPARA_CONT_DIA_SEM = "COMPARA_CONT_DIA_SEM";
        public const string INDICA_MIN_CONT_DIA_MES = "INDICA_MIN_CONT_DIA_MES";
        public const string COMPARA_CONT_DIA_MES = "COMPARA_CONT_DIA_MES";
        public const string INDICA_MIN_CONT_DIA_MOD = "INDICA_MIN_CONT_DIA_MOD";
        public const string COMPARA_CONT_DIA_MOD = "COMPARA_CONT_DIA_MOD";
        public const string INDICA_MIN_CONT_MES = "INDICA_MIN_CONT_MES";
        public const string COMPARA_CONT_MES = "COMPARA_CONT_MES";
        public const string COMPARA_CONT_DESP_ACTUAL = "COMPARA_CONT_DESP_ACTUAL";
        public const string INDICA_MIN_CONT_DESP_ACTUAL = "INDICA_MIN_CONT_DESP_ACTUAL";
        public const string INDICA_MIN_PUNTUA_TOTAL = "INDICA_MIN_PUNTUA_TOTAL";
        public const string INDICA_MAX_PUNTUA_TOTAL = "INDICA_MAX_PUNTUA_TOTAL";
        public const string INDICA_MIN_SUMATORIA = "INDICA_MIN_SUMATORIA";
        public const string INDICA_MAX_SUMATORIA = "INDICA_MAX_SUMATORIA";
        public const string DATOS_TEMP = "DATOS_TEMP";
        public const string AN_DAT_SIGN = "AN_DAT_SIGN";
        public const string AN_DAT_POS_CUATRO = "AN_DAT_POS_CUATRO";
        public const string AN_DAT_POS_TRES = "AN_DAT_POS_TRES";
        public const string AN_DAT_POS_DOS = "AN_DAT_POS_DOS";
        public const string AN_DAT_POS_UNO = "AN_DAT_POS_UNO";
        public const string POS_CUATRO_DATOS = "POS_CUATRO_DATOS";
        public const string POS_DOS_DATOS = "POS_DOS_DATOS";
        public const string POS_TRES_DATOS = "POS_TRES_DATOS";
        public const string POS_UNO_DATOS = "POS_UNO_DATOS";
        public const string SIGN_DATOS = "SIGN_DATOS";
        public const string CONTADORULTIMOENRACHAS = "CONTADORULTIMOENRACHAS";
        public const string CONTADORULTIMOENRACHASDESACTUA = "CONTADORULTIMOENRACHASDESACTUA";
        public const string CONTADORGENERAL = "CONTADORGENERAL";
        public const string CONTADORDIASEMANA = "CONTADORDIASEMANA";
        public const string CONTADORDIAMES = "CONTADORDIAMES";
        public const string CONTADORDIAMODULO = "CONTADORDIAMODULO";
        public const string CONTADORMES = "CONTADORMES";
        public const string CONTADORDESPUESACTUAL = "CONTADORDESPUESACTUAL";
        public const string CONTADORDIAANIO = "CONTADORDIAANIO";
        public const string CONTADORDIAANIOMODULO = "CONTADORDIAANIOMODULO";
        public const string CONTADORMESMODULODIAMODULO = "CONTADORMESMODULODIAMODULO";
        public const string CONTADORMESDIA = "CONTADORMESDIA";
        public const string CONTADORANIOMODULO = "CONTADORANIOMODULO";
        public const string CONTADORMESMODULO = "CONTADORMESMODULO";
        public const string CONTADORDESPUESOTROTIPO = "CONTADORDESPUESOTROTIPO";
        public const string CONTADORDESPUESSIGNACTUAL = "CONTADORDESPUESSIGNACTUAL";
        public const string SUMATORIAVALORES = "SUMATORIAVALORES";
        public const string INDICAMINSINAPARECER = "indicaMinSinAparecer";
        public const string INDICAMINULTRACH = "indicaMinUltRach";
        public const string COMPARAULTRACHAS = "comparaUltRachas";
        public const string INDICAMINCONTGENERAL = "indicaMinContGeneral";
        public const string INDICACOMPARACONTGENERAL = "indicaComparaContGeneral";
        public const string INDICAMINCONTDIASEMANA = "indicaMinContDiaSemana";
        public const string INDICACOMPARACONTDIASEMANA = "indicaComparaContDiaSemana";
        public const string INDICAMINDIAMES = "indicaMinDiaMes";
        public const string INDICACOMPARACONTDIAMES = "indicaComparaContDiaMes";
        public const string INDICAMINDIAMOD = "indicaMinDiaMod";
        public const string INDICACOMPARACONTDIAMOD = "indicaComparaContDiaMod";
        public const string INDICAMINMES = "indicaMinMes";
        public const string INDICACOMPARACONTMES = "indicaComparaContMes";
        public const string INDICAMINDESPACTUAL = "indicaMinDespActual";
        public const string INDICACOMPARACONTDESPACTUAL = "indicaComparaContDespActual";
        public const string INDICAMINPUNTUATOTAL = "indicaMinPuntuaTotal";
        public const string INDICAMAXPUNTUATOTAL = "indicaMaxPuntuaTotal";
        public const string INDICAMINSUMATORIA = "indicaMinSumatoria";
        public const string INDICAMAXSUMATORIA = "indicaMaxSumatoria";
    }
}
