select count(*) from sign_datos where abs(SINAPARECER) = CONTADORULTIMOENRACHAS  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 5 and abs(SINAPARECER) = CONTADORULTIMOENRACHAS  and fecha >= sysdate -31 order by fecha desc;
select count(*) from sign_datos where abs(SINAPARECER) = CONTADORGENERAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 5 and abs(SINAPARECER) = CONTADORGENERAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from sign_datos where abs(SINAPARECER) = CONTADORDIASEMANA  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 5 and abs(SINAPARECER) = CONTADORDIASEMANA  and fecha >= sysdate -31 order by fecha desc;
select count(*) from sign_datos where abs(SINAPARECER) = CONTADORDIAMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 5 and abs(SINAPARECER) = CONTADORDIAMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from sign_datos where abs(SINAPARECER) = CONTADORDIAMODULO  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 5 and abs(SINAPARECER) = CONTADORDIAMODULO  and fecha >= sysdate -31 order by fecha desc;
select count(*) from sign_datos where abs(SINAPARECER) = CONTADORMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 5 and abs(SINAPARECER) = CONTADORMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from sign_datos where abs(SINAPARECER) = CONTADORDESPUESACTUAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 5 and abs(SINAPARECER) = CONTADORDESPUESACTUAL  and fecha >= sysdate -31 order by fecha desc;

select count(*) from pos_cuatro_datos where abs(SINAPARECER) = CONTADORULTIMOENRACHAS  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 4 and abs(SINAPARECER) = CONTADORULTIMOENRACHAS  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_cuatro_datos where abs(SINAPARECER) = CONTADORGENERAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 4 and abs(SINAPARECER) = CONTADORGENERAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_cuatro_datos where abs(SINAPARECER) = CONTADORDIASEMANA  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 4 and abs(SINAPARECER) = CONTADORDIASEMANA  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_cuatro_datos where abs(SINAPARECER) = CONTADORDIAMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 4 and abs(SINAPARECER) = CONTADORDIAMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_cuatro_datos where abs(SINAPARECER) = CONTADORDIAMODULO  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 4 and abs(SINAPARECER) = CONTADORDIAMODULO  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_cuatro_datos where abs(SINAPARECER) = CONTADORMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 4 and abs(SINAPARECER) = CONTADORMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_cuatro_datos where abs(SINAPARECER) = CONTADORDESPUESACTUAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 4 and abs(SINAPARECER) = CONTADORDESPUESACTUAL  and fecha >= sysdate -31 order by fecha desc;

select count(*) from pos_tres_datos where abs(SINAPARECER) = CONTADORULTIMOENRACHAS  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 3 and abs(SINAPARECER) = CONTADORULTIMOENRACHAS  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_tres_datos where abs(SINAPARECER) = CONTADORGENERAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 3 and abs(SINAPARECER) = CONTADORGENERAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_tres_datos where abs(SINAPARECER) = CONTADORDIASEMANA  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 3 and abs(SINAPARECER) = CONTADORDIASEMANA  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_tres_datos where abs(SINAPARECER) = CONTADORDIAMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 3 and abs(SINAPARECER) = CONTADORDIAMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_tres_datos where abs(SINAPARECER) = CONTADORDIAMODULO  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 3 and abs(SINAPARECER) = CONTADORDIAMODULO  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_tres_datos where abs(SINAPARECER) = CONTADORMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 3 and abs(SINAPARECER) = CONTADORMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_tres_datos where abs(SINAPARECER) = CONTADORDESPUESACTUAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 3 and abs(SINAPARECER) = CONTADORDESPUESACTUAL  and fecha >= sysdate -31 order by fecha desc;

select count(*) from pos_dos_datos where abs(SINAPARECER) = CONTADORULTIMOENRACHAS  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 2 and abs(SINAPARECER) = CONTADORULTIMOENRACHAS  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_dos_datos where abs(SINAPARECER) = CONTADORGENERAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 2 and abs(SINAPARECER) = CONTADORGENERAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_dos_datos where abs(SINAPARECER) = CONTADORDIASEMANA  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 2 and abs(SINAPARECER) = CONTADORDIASEMANA  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_dos_datos where abs(SINAPARECER) = CONTADORDIAMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 2 and abs(SINAPARECER) = CONTADORDIAMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_dos_datos where abs(SINAPARECER) = CONTADORDIAMODULO  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 2 and abs(SINAPARECER) = CONTADORDIAMODULO  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_dos_datos where abs(SINAPARECER) = CONTADORMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 2 and abs(SINAPARECER) = CONTADORMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_dos_datos where abs(SINAPARECER) = CONTADORDESPUESACTUAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 2 and abs(SINAPARECER) = CONTADORDESPUESACTUAL  and fecha >= sysdate -31 order by fecha desc;

select count(*) from pos_uno_datos where abs(SINAPARECER) = CONTADORULTIMOENRACHAS  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 1 and abs(SINAPARECER) = CONTADORULTIMOENRACHAS  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_uno_datos where abs(SINAPARECER) = CONTADORGENERAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 1 and abs(SINAPARECER) = CONTADORGENERAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_uno_datos where abs(SINAPARECER) = CONTADORDIASEMANA  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 1 and abs(SINAPARECER) = CONTADORDIASEMANA  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_uno_datos where abs(SINAPARECER) = CONTADORDIAMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 1 and abs(SINAPARECER) = CONTADORDIAMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_uno_datos where abs(SINAPARECER) = CONTADORDIAMODULO  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 1 and abs(SINAPARECER) = CONTADORDIAMODULO  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_uno_datos where abs(SINAPARECER) = CONTADORMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 1 and abs(SINAPARECER) = CONTADORMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from pos_uno_datos where abs(SINAPARECER) = CONTADORDESPUESACTUAL  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 1 and abs(SINAPARECER) = CONTADORDESPUESACTUAL  and fecha >= sysdate -31 order by fecha desc;

select count(*) from sign_datos where CONTADORDIASEMANA = CONTADORGENERAL and CONTADORDIASEMANA = CONTADORDIAMES  and fecha >= sysdate -31 order by fecha desc;
select count(*) from datos_temp where posicion = 5 and CONTADORDIASEMANA = CONTADORGENERAL and CONTADORDIASEMANA = CONTADORDIAMES  and fecha >= sysdate -31 order by fecha desc;