CREATE USER userSort IDENTIFIED BY userSort;
GRANT RESOURCE TO userSort;
GRANT CREATE SESSION TO userSort;

CREATE TABLE ASTR(
	ID NUMBER primary key,
	TIPO NUMBER(1),
	POS_UNO NUMBER(1),
	POS_DOS NUMBER(1),
	POS_TRES NUMBER(1),
	POS_CUATRO NUMBER(1), 
	SIGN VARCHAR2(15), 
	NUM_SOR NUMBER(6),
	FECHA DATE
	);


CREATE OR REPLACE SEQUENCE  SQ_ASTR  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
create or replace trigger TR_INSERT_ASTR
before insert on ASTR
for each row
begin
  select SQ_ASTR.nextval into :new.Id from dual;
end;
/