//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DataContextModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AN_DAT_POS_TRES
    {
        public decimal ID { get; set; }
        public Nullable<decimal> INDICA_MIN_SIN_APARECER { get; set; }
        public Nullable<decimal> INDICA_MIN_ULT_RACH { get; set; }
        public Nullable<decimal> COMPARA_ULT_RACH { get; set; }
        public Nullable<decimal> INDICA_MIN_CONT_GENERAL { get; set; }
        public Nullable<decimal> COMPARA_CONT_GENERAL { get; set; }
        public Nullable<decimal> INDICA_MIN_CONT_DIA_SEM { get; set; }
        public Nullable<decimal> COMPARA_CONT_DIA_SEM { get; set; }
        public Nullable<decimal> INDICA_MIN_CONT_DIA_MES { get; set; }
        public Nullable<decimal> COMPARA_CONT_DIA_MES { get; set; }
        public Nullable<decimal> INDICA_MIN_CONT_DIA_MOD { get; set; }
        public Nullable<decimal> COMPARA_CONT_DIA_MOD { get; set; }
        public Nullable<decimal> INDICA_MIN_CONT_MES { get; set; }
        public Nullable<decimal> COMPARA_CONT_MES { get; set; }
        public Nullable<decimal> INDICA_MIN_CONT_DESP_ACTUAL { get; set; }
        public Nullable<decimal> COMPARA_CONT_DESP_ACTUAL { get; set; }
        public Nullable<decimal> INDICA_MIN_PUNTUA_TOTAL { get; set; }
        public Nullable<decimal> INDICA_MAX_PUNTUA_TOTAL { get; set; }
        public Nullable<decimal> DIAMES { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
