//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DataContextModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_TEMP
    {
        public decimal ID { get; set; }
        public Nullable<decimal> POSICION { get; set; }
        public Nullable<decimal> TIPO { get; set; }
        public Nullable<decimal> CLAVE { get; set; }
        public string CLAVESIGN { get; set; }
        public Nullable<decimal> PUNTUACIONTOTAL { get; set; }
        public Nullable<decimal> CONTADORULTIMOENRACHAS { get; set; }
        public Nullable<decimal> CONTADORULTIMOENRACHASDESACTUA { get; set; }
        public Nullable<decimal> CONTADORGENERAL { get; set; }
        public Nullable<decimal> CONTADORDIASEMANA { get; set; }
        public Nullable<decimal> CONTADORDIAMES { get; set; }
        public Nullable<decimal> CONTADORDIAMODULO { get; set; }
        public Nullable<decimal> CONTADORMES { get; set; }
        public Nullable<decimal> CONTADORDIAANIO { get; set; }
        public Nullable<decimal> CONTADORDIAANIOMODULO { get; set; }
        public Nullable<decimal> CONTADORMESMODULODIAMODULO { get; set; }
        public Nullable<decimal> CONTADORMESDIA { get; set; }
        public Nullable<decimal> CONTADORANIOMODULO { get; set; }
        public Nullable<decimal> CONTADORMESMODULO { get; set; }
        public Nullable<decimal> CONTADORDESPUESACTUAL { get; set; }
        public Nullable<decimal> CONTADORDESPUESOTROTIPO { get; set; }
        public Nullable<decimal> CONTADORDESPUESSIGNACTUAL { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
