//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DataContextModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_TRES_DATOS
    {
        public int ID { get; set; }
        public Nullable<int> TIPO { get; set; }
        public Nullable<int> PUNTUACIONTOTAL { get; set; }
        public Nullable<int> CONTADORULTIMOENRACHAS { get; set; }
        public Nullable<int> CONTADORULTIMOENRACHASDESACTUA { get; set; }
        public Nullable<int> CONTADORGENERAL { get; set; }
        public Nullable<int> CONTADORDIASEMANA { get; set; }
        public Nullable<int> CONTADORDIAMES { get; set; }
        public Nullable<int> CONTADORDIAMODULO { get; set; }
        public Nullable<int> CONTADORMES { get; set; }
        public Nullable<int> CONTADORDIAANIO { get; set; }
        public Nullable<int> CONTADORDIAANIOMODULO { get; set; }
        public Nullable<int> CONTADORMESMODULODIAMODULO { get; set; }
        public Nullable<int> CONTADORMESDIA { get; set; }
        public Nullable<int> CONTADORANIOMODULO { get; set; }
        public Nullable<int> CONTADORMESMODULO { get; set; }
        public Nullable<int> CONTADORDESPUESACTUAL { get; set; }
        public Nullable<int> CONTADORDESPUESOTROTIPO { get; set; }
        public Nullable<int> CONTADORDESPUESSIGNACTUAL { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
