//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DataContextModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGN_DATOS
    {
        public decimal ID { get; set; }
        public Nullable<decimal> TIPO { get; set; }
        public Nullable<decimal> PUNTUACIONTOTAL { get; set; }
        public Nullable<decimal> SINAPARECER { get; set; }
        public Nullable<decimal> CONTADORULTIMOENRACHAS { get; set; }
        public Nullable<decimal> CONTADORULTIMOENRACHASDESACTUA { get; set; }
        public Nullable<decimal> CONTADORGENERAL { get; set; }
        public Nullable<decimal> CONTADORDIASEMANA { get; set; }
        public Nullable<decimal> CONTADORDIAMES { get; set; }
        public Nullable<decimal> CONTADORDIAMODULO { get; set; }
        public Nullable<decimal> CONTADORMES { get; set; }
        public Nullable<decimal> CONTADORDESPUESACTUAL { get; set; }
        public Nullable<decimal> SUMATORIAVALORES { get; set; }
        public Nullable<decimal> CONTADORDESPUESSIGNACTUAL { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
